  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP1BZ76b545JWtCXg3N5cEO-Os5Baq_uU',
    appId: '1:797572013164:web:0abc82b25b123e9065cc49',
    messagingSenderId: '797572013164',
    projectId: 'abimind-2caf8',
    authDomain: 'abimind-2caf8.firebaseapp.com',
    storageBucket: 'abimind-2caf8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3vJrgfNHPiMstzDukGpCCcWOLOpDc_E',
    appId: '1:797572013164:android:69046c3c2f5c73e265cc49',
    messagingSenderId: '797572013164',
    projectId: 'abimind-2caf8',
    storageBucket: 'abimind-2caf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5LXZFD6mIPc94U_CGKakBlJS8zWopJTY',
    appId: '1:797572013164:ios:4b153aa50fc45ef865cc49',
    messagingSenderId: '797572013164',
    projectId: 'abimind-2caf8',
    storageBucket: 'abimind-2caf8.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5LXZFD6mIPc94U_CGKakBlJS8zWopJTY',
    appId: '1:797572013164:ios:4b153aa50fc45ef865cc49',
    messagingSenderId: '797572013164',
    projectId: 'abimind-2caf8',
    storageBucket: 'abimind-2caf8.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP1BZ76b545JWtCXg3N5cEO-Os5Baq_uU',
    appId: '1:797572013164:web:8d3ba5692f3aeb5065cc49',
    messagingSenderId: '797572013164',
    projectId: 'abimind-2caf8',
    authDomain: 'abimind-2caf8.firebaseapp.com',
    storageBucket: 'abimind-2caf8.firebasestorage.app',
  );
}
